# Generated by Django 5.1.4 on 2025-01-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512, unique=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_descriptions', to='educations_app.education')),
            ],
            options={
                'db_table': 'education_descriptions',
            },
        ),
    ]
