# Generated by Django 5.1.4 on 2025-01-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations_app', '0003_alter_educationdescription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='date_start',
            new_name='start_date',
        ),
    ]
