# Generated by Django 5.1.4 on 2025-01-18 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences_app', '0002_experiencedescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='experiencedescription',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'title')},
        ),
    ]
