# Generated by Django 5.1.4 on 2025-01-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.skillcategory')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
