# Generated by Django 5.1.4 on 2025-01-18 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill_category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='skillcategory',
            unique_together={('user', 'category')},
        ),
    ]
